// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockTrading.proto

package dev.tanpn.grpc.proto;

public interface CancelOrderReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stock.CancelOrderReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .stock.CancelOrderReplyDetail responses = 1;</code>
   */
  java.util.List<dev.tanpn.grpc.proto.CancelOrderReplyDetail> 
      getResponsesList();
  /**
   * <code>repeated .stock.CancelOrderReplyDetail responses = 1;</code>
   */
  dev.tanpn.grpc.proto.CancelOrderReplyDetail getResponses(int index);
  /**
   * <code>repeated .stock.CancelOrderReplyDetail responses = 1;</code>
   */
  int getResponsesCount();
  /**
   * <code>repeated .stock.CancelOrderReplyDetail responses = 1;</code>
   */
  java.util.List<? extends dev.tanpn.grpc.proto.CancelOrderReplyDetailOrBuilder> 
      getResponsesOrBuilderList();
  /**
   * <code>repeated .stock.CancelOrderReplyDetail responses = 1;</code>
   */
  dev.tanpn.grpc.proto.CancelOrderReplyDetailOrBuilder getResponsesOrBuilder(
      int index);
}
