// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageStreaming.proto

package dev.tanpn.grpc.proto;

public interface MessageDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stock.MessageDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageType = 1;</code>
   */
  java.lang.String getMessageType();
  /**
   * <code>string messageType = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageTypeBytes();

  /**
   * <code>string data = 2;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
