// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockTrading.proto

package dev.tanpn.grpc.proto;

/**
 * Protobuf type {@code stock.OrderEnquiryRequest}
 */
public  final class OrderEnquiryRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:stock.OrderEnquiryRequest)
    OrderEnquiryRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderEnquiryRequest.newBuilder() to construct.
  private OrderEnquiryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderEnquiryRequest() {
    clientID_ = "";
    stockID_ = "";
    marketID_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderEnquiryRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            clientID_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            stockID_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            marketID_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.tanpn.grpc.proto.StockTradingSvc.internal_static_stock_OrderEnquiryRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.tanpn.grpc.proto.StockTradingSvc.internal_static_stock_OrderEnquiryRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.tanpn.grpc.proto.OrderEnquiryRequest.class, dev.tanpn.grpc.proto.OrderEnquiryRequest.Builder.class);
  }

  public static final int CLIENTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object clientID_;
  /**
   * <code>string clientID = 1;</code>
   */
  public java.lang.String getClientID() {
    java.lang.Object ref = clientID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientID_ = s;
      return s;
    }
  }
  /**
   * <code>string clientID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getClientIDBytes() {
    java.lang.Object ref = clientID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STOCKID_FIELD_NUMBER = 2;
  private volatile java.lang.Object stockID_;
  /**
   * <code>string stockID = 2;</code>
   */
  public java.lang.String getStockID() {
    java.lang.Object ref = stockID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stockID_ = s;
      return s;
    }
  }
  /**
   * <code>string stockID = 2;</code>
   */
  public com.google.protobuf.ByteString
      getStockIDBytes() {
    java.lang.Object ref = stockID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stockID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MARKETID_FIELD_NUMBER = 3;
  private volatile java.lang.Object marketID_;
  /**
   * <code>string marketID = 3;</code>
   */
  public java.lang.String getMarketID() {
    java.lang.Object ref = marketID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      marketID_ = s;
      return s;
    }
  }
  /**
   * <code>string marketID = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMarketIDBytes() {
    java.lang.Object ref = marketID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      marketID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClientIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientID_);
    }
    if (!getStockIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stockID_);
    }
    if (!getMarketIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, marketID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClientIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientID_);
    }
    if (!getStockIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stockID_);
    }
    if (!getMarketIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, marketID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.tanpn.grpc.proto.OrderEnquiryRequest)) {
      return super.equals(obj);
    }
    dev.tanpn.grpc.proto.OrderEnquiryRequest other = (dev.tanpn.grpc.proto.OrderEnquiryRequest) obj;

    if (!getClientID()
        .equals(other.getClientID())) return false;
    if (!getStockID()
        .equals(other.getStockID())) return false;
    if (!getMarketID()
        .equals(other.getMarketID())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getClientID().hashCode();
    hash = (37 * hash) + STOCKID_FIELD_NUMBER;
    hash = (53 * hash) + getStockID().hashCode();
    hash = (37 * hash) + MARKETID_FIELD_NUMBER;
    hash = (53 * hash) + getMarketID().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.tanpn.grpc.proto.OrderEnquiryRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.tanpn.grpc.proto.OrderEnquiryRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.tanpn.grpc.proto.OrderEnquiryRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.tanpn.grpc.proto.OrderEnquiryRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.tanpn.grpc.proto.OrderEnquiryRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.tanpn.grpc.proto.OrderEnquiryRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.tanpn.grpc.proto.OrderEnquiryRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.tanpn.grpc.proto.OrderEnquiryRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.tanpn.grpc.proto.OrderEnquiryRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dev.tanpn.grpc.proto.OrderEnquiryRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.tanpn.grpc.proto.OrderEnquiryRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.tanpn.grpc.proto.OrderEnquiryRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.tanpn.grpc.proto.OrderEnquiryRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code stock.OrderEnquiryRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stock.OrderEnquiryRequest)
      dev.tanpn.grpc.proto.OrderEnquiryRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.tanpn.grpc.proto.StockTradingSvc.internal_static_stock_OrderEnquiryRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.tanpn.grpc.proto.StockTradingSvc.internal_static_stock_OrderEnquiryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.tanpn.grpc.proto.OrderEnquiryRequest.class, dev.tanpn.grpc.proto.OrderEnquiryRequest.Builder.class);
    }

    // Construct using dev.tanpn.grpc.proto.OrderEnquiryRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clientID_ = "";

      stockID_ = "";

      marketID_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.tanpn.grpc.proto.StockTradingSvc.internal_static_stock_OrderEnquiryRequest_descriptor;
    }

    @java.lang.Override
    public dev.tanpn.grpc.proto.OrderEnquiryRequest getDefaultInstanceForType() {
      return dev.tanpn.grpc.proto.OrderEnquiryRequest.getDefaultInstance();
    }

    @java.lang.Override
    public dev.tanpn.grpc.proto.OrderEnquiryRequest build() {
      dev.tanpn.grpc.proto.OrderEnquiryRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.tanpn.grpc.proto.OrderEnquiryRequest buildPartial() {
      dev.tanpn.grpc.proto.OrderEnquiryRequest result = new dev.tanpn.grpc.proto.OrderEnquiryRequest(this);
      result.clientID_ = clientID_;
      result.stockID_ = stockID_;
      result.marketID_ = marketID_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.tanpn.grpc.proto.OrderEnquiryRequest) {
        return mergeFrom((dev.tanpn.grpc.proto.OrderEnquiryRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.tanpn.grpc.proto.OrderEnquiryRequest other) {
      if (other == dev.tanpn.grpc.proto.OrderEnquiryRequest.getDefaultInstance()) return this;
      if (!other.getClientID().isEmpty()) {
        clientID_ = other.clientID_;
        onChanged();
      }
      if (!other.getStockID().isEmpty()) {
        stockID_ = other.stockID_;
        onChanged();
      }
      if (!other.getMarketID().isEmpty()) {
        marketID_ = other.marketID_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dev.tanpn.grpc.proto.OrderEnquiryRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dev.tanpn.grpc.proto.OrderEnquiryRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object clientID_ = "";
    /**
     * <code>string clientID = 1;</code>
     */
    public java.lang.String getClientID() {
      java.lang.Object ref = clientID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clientID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientIDBytes() {
      java.lang.Object ref = clientID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientID = 1;</code>
     */
    public Builder setClientID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clientID = 1;</code>
     */
    public Builder clearClientID() {
      
      clientID_ = getDefaultInstance().getClientID();
      onChanged();
      return this;
    }
    /**
     * <code>string clientID = 1;</code>
     */
    public Builder setClientIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object stockID_ = "";
    /**
     * <code>string stockID = 2;</code>
     */
    public java.lang.String getStockID() {
      java.lang.Object ref = stockID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stockID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stockID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStockIDBytes() {
      java.lang.Object ref = stockID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stockID = 2;</code>
     */
    public Builder setStockID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stockID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stockID = 2;</code>
     */
    public Builder clearStockID() {
      
      stockID_ = getDefaultInstance().getStockID();
      onChanged();
      return this;
    }
    /**
     * <code>string stockID = 2;</code>
     */
    public Builder setStockIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stockID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object marketID_ = "";
    /**
     * <code>string marketID = 3;</code>
     */
    public java.lang.String getMarketID() {
      java.lang.Object ref = marketID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        marketID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string marketID = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMarketIDBytes() {
      java.lang.Object ref = marketID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        marketID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string marketID = 3;</code>
     */
    public Builder setMarketID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      marketID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string marketID = 3;</code>
     */
    public Builder clearMarketID() {
      
      marketID_ = getDefaultInstance().getMarketID();
      onChanged();
      return this;
    }
    /**
     * <code>string marketID = 3;</code>
     */
    public Builder setMarketIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      marketID_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:stock.OrderEnquiryRequest)
  }

  // @@protoc_insertion_point(class_scope:stock.OrderEnquiryRequest)
  private static final dev.tanpn.grpc.proto.OrderEnquiryRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.tanpn.grpc.proto.OrderEnquiryRequest();
  }

  public static dev.tanpn.grpc.proto.OrderEnquiryRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderEnquiryRequest>
      PARSER = new com.google.protobuf.AbstractParser<OrderEnquiryRequest>() {
    @java.lang.Override
    public OrderEnquiryRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderEnquiryRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderEnquiryRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderEnquiryRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.tanpn.grpc.proto.OrderEnquiryRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

