// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockTrading.proto

package dev.tanpn.grpc.proto;

public interface CancelOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stock.CancelOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.OrderDetail orderDetail = 1;</code>
   */
  boolean hasOrderDetail();
  /**
   * <code>.OrderDetail orderDetail = 1;</code>
   */
  dev.tanpn.grpc.proto.OrderDetail getOrderDetail();
  /**
   * <code>.OrderDetail orderDetail = 1;</code>
   */
  dev.tanpn.grpc.proto.OrderDetailOrBuilder getOrderDetailOrBuilder();
}
