// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockTrading.proto

package dev.tanpn.grpc.proto;

public interface EnterOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stock.EnterOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientID = 1;</code>
   */
  java.lang.String getClientID();
  /**
   * <code>string clientID = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientIDBytes();

  /**
   * <code>string stockID = 2;</code>
   */
  java.lang.String getStockID();
  /**
   * <code>string stockID = 2;</code>
   */
  com.google.protobuf.ByteString
      getStockIDBytes();

  /**
   * <code>string marketID = 3;</code>
   */
  java.lang.String getMarketID();
  /**
   * <code>string marketID = 3;</code>
   */
  com.google.protobuf.ByteString
      getMarketIDBytes();

  /**
   * <code>int32 quantity = 4;</code>
   */
  int getQuantity();

  /**
   * <code>double price = 5;</code>
   */
  double getPrice();
}
