// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/common.proto

package dev.tanpn.grpc.proto;

public interface OrderDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientID = 1;</code>
   */
  java.lang.String getClientID();
  /**
   * <code>string clientID = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientIDBytes();

  /**
   * <code>string orderID = 2;</code>
   */
  java.lang.String getOrderID();
  /**
   * <code>string orderID = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrderIDBytes();

  /**
   * <code>int32 quantity = 3;</code>
   */
  int getQuantity();

  /**
   * <code>double price = 4;</code>
   */
  double getPrice();

  /**
   * <code>.OrderStatus status = 5;</code>
   */
  int getStatusValue();
  /**
   * <code>.OrderStatus status = 5;</code>
   */
  dev.tanpn.grpc.proto.OrderStatus getStatus();
}
