// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockTrading.proto

package dev.tanpn.grpc.proto;

public interface OrderEnquiryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stock.OrderEnquiryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientID = 1;</code>
   */
  java.lang.String getClientID();
  /**
   * <code>string clientID = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientIDBytes();

  /**
   * <code>string stockID = 2;</code>
   */
  java.lang.String getStockID();
  /**
   * <code>string stockID = 2;</code>
   */
  com.google.protobuf.ByteString
      getStockIDBytes();

  /**
   * <code>string marketID = 3;</code>
   */
  java.lang.String getMarketID();
  /**
   * <code>string marketID = 3;</code>
   */
  com.google.protobuf.ByteString
      getMarketIDBytes();
}
